package core.ia;

public enum TypeAIPlayer {
    CHOOSE_FIRST,
    RANDOM,
    PREF_CRYSTALLIZE,
    PREF_CARD_POINTS,
    PREF_INVOCATION,
    COMBOS,
    MALUS,
    TIME_FIRST,
    TIME_RANDOM,
    TIME_CRYSTALLIZE,
    TIME_INVOCATION,
    COMPOSE1,
    ACTIVATE,
    PREF_PERMANENT,
    DYL_COMPOSE,
    COMPOSE_MARG,
    COMPOSE_RAPH,
    ADAPTATIVE,
    MONTECARLO,
    MONTECARLO_COMPOSE,
    ERROR;
}
