package core.game;

public enum ChoiceType {
    CHOOSE_CARDS_TO_BEGIN, DICE, USE_DE_DE_LA_MALICE, CHOOSE_TO_USE_BONUS_CARD,
    CHOOSE_PLAYER_ACTION, CHOOSE_ENERGY_TO_CRYSTALLIZE, CHOOSE_CARD_TO_SUMMON, CHOOSE_BONUS_TO_USE,
    CHOOSE_CARD_TO_ACTIVATE, CHOOSE_ENERGY_TO_THROW;
    // Les choix dans les cartes

}
